package se.antons_skafferi.sqlDataClasses;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
// This means that this class is a Controller
@RestController
@RequestMapping(path="/menu") // api path from localhost:8080
 /*
  Controller for the menu
 */
public class MenuController {

    @Autowired// This means to get the bean called MenuRepository
    // Which is auto-generated by Spring, we will use it to handle the data

    private DatabaseService databaseService;

    /**
     * Get all menu items
     * @return List of all menu items at the endpoint as JSON
     */
    @GetMapping(path="/all")
    public List<Food> getAllMenuItems() {
        return databaseService.getMenuItems();
    }

    @GetMapping(path="/lunch")
    public List<DailyLunch> getLunchMenuItems() {
        return databaseService.getLunchMenuItems();
    }

    @GetMapping(path="/dinner")
    public List<DinnerMenuItem> getDinnerMenuItems() {
        return databaseService.getDinnerMenuItems();
    }
}