package se.antons_skafferi.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import se.antons_skafferi.service.DatabaseService;

import java.util.List;
// This means that this class is a Controller
@RestController
@RequestMapping(path="/api") // api path from localhost:8080
 /*
  Controller for the menu
 */
public class APIController {

    @Autowired// This means to get the bean called MenuRepository
    // Which is auto-generated by Spring, we will use it to handle the data

    private DatabaseService databaseService;

    @GetMapping(path="/menu/{type}")
    public List<?> getMenuItems(@PathVariable String type) {
        return switch (type.toLowerCase()) {
            case "all" -> databaseService.getMenuItems();
            case "lunch" -> databaseService.getLunchMenuItems();
            case "dinner" -> databaseService.getDinnerMenuItems();
            default -> throw new IllegalArgumentException("Invalid menu type: " + type);
        };
    }
    // Ignore the "to few switch cases" warning, we will add more cases as we add more types of bookings.
    @GetMapping(path="/calendar/bookings/{type}")
    public List<?> getBookings(@PathVariable String type) {
        return switch (type.toLowerCase()) {
            case "all" -> databaseService.getBookings();
            // Add more cases if needed for different types of bookings
            default -> throw new IllegalArgumentException("Invalid booking type: " + type);
        };
    }
}