SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS contains;
DROP TABLE IF EXISTS for_lunch;
DROP TABLE IF EXISTS food;
DROP TABLE IF EXISTS works_at;
DROP TABLE IF EXISTS works_as;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS shift;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS tables;
DROP TABLE IF EXISTS ingredients;
DROP TABLE IF EXISTS dinner_menu;
DROP TABLE IF EXISTS lunch;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS person;

SET FOREIGN_KEY_CHECKS=1;